version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - echo ${env.CODEARTIFACT_TOKEN}
      - echo ${CODEARTIFACT_TOKEN}
      - mvn test -X -Pruslanzdor--gram-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -Pruslanzdor--gram-repo
artifacts:
  files:
    - target/tubegram-1.0.jar
    - appspec.yml
  discard-paths: yes