version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - aws codeartifact login --tool maven --repository gram-repo --domain ruslanzdor --domain-owner 244092297712
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/tubegram-1.0.jar
    - appspec.yml
  discard-paths: yes