version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - echo Build started on `date`
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain ruslanzdor --domain-owner 244092297712 --query authorizationToken --output text`
  build:
    commands:
      - mvn test
      - aws cloudformation package --template-file template-mvn.yml --s3-bucket gram-deploy --output-template-file out.yml
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn deploy
artifacts:
  files:
    - target/eventgram-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes