version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - echo Build started on `date`
      - echo $CODEARTIFACT_TOKEN
      - echo ${env.CODEARTIFACT_TOKEN}
      - echo CODEARTIFACT_PATH
      - echo ${env.CODEARTIFACT_PATH}
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/tubegram-1.0.jar
    - appspec.yml
  discard-paths: yes