server:
  port: 8090
spring:
  application:
    name: event-gram
logging:
  level:
    org:
      springframework: INFO
    com: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
